#build environment
# base image
#FROM node:8.12.0 as builder
FROM node:10.11.0

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install --silent
#RUN npm install react-scripts@1.1.5 -g --silent
COPY . /usr/src/app/
EXPOSE 3001

#ENTRYPOINT ["node", "server/server.js"]
#RUN node server/server.js
CMD ["npm", "run", "start:server"]


#production environment
#FROM nginx
#COPY --from=builder /usr/src/app/public /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]